const modes=['vanilla','uhc','pot','nethop','smp','sword','axe','mace'];
const modeNames={vanilla:'Vanilla',uhc:'UHC',pot:'Pot',nethop:'NetHop',smp:'SMP',sword:'Sword',axe:'Axe',mace:'Mace'};
let players=[];
const $=id=>document.getElementById(id);
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data;}
function showTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tabpage').forEach(x=>x.classList.toggle('hidden',x.id!==id));$('pageTitle').textContent={dashboard:'Dashboard',players:'Players',icons:'Mode Icons',security:'Security'}[id];if(id==='players')renderPlayers();if(id==='icons')loadSettings();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
async function check(){try{const me=await api('/api/admin/me');$('adminEmail').textContent=me.email;$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadPlayers();}catch{}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='';try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});$('adminEmail').textContent=d.email;$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadPlayers();}catch(err){$('loginMsg').textContent=err.message}};
$('logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};
async function loadPlayers(){const d=await api('/api/admin/players');players=d.players;updateStats();renderPlayers();}
function updateStats(){let results=0,tested=0;players.forEach(p=>modes.forEach(m=>{if(p.results[m] && (p.results[m].tier||p.results[m].points!==null)){results++;tested++;}}));$('statPlayers').textContent=players.length;$('statTested').textContent=new Set(players.filter(p=>modes.some(m=>p.results[m]&&(p.results[m].tier||p.results[m].points!==null))).map(p=>p.id)).size;$('statResults').textContent=results;}
function renderPlayers(){const q=($('playerSearch').value||'').toLowerCase();const arr=players.filter(p=>p.name.toLowerCase().includes(q));$('playerList').innerHTML=arr.length?arr.map(p=>{let count=modes.filter(m=>p.results[m]&&(p.results[m].tier||p.results[m].points!==null)).length;return `<div class="player-card"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.region)} • ${count} tested modes • ${p.skin_url?'Custom skin URL':'Username skin fallback'}</small></div><div><small>ID #${p.id}</small></div><div class="player-actions"><button data-edit="${p.id}">Edit</button><button class="danger" data-del="${p.id}">Delete</button></div></div>`}).join(''):'<div class="panel"><p>No players found.</p></div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(Number(b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deletePlayer(Number(b.dataset.del)));}
$('playerSearch').oninput=renderPlayers;
$('addPlayer').onclick=()=>openEditor();
function openEditor(id){const p=players.find(x=>x.id===id);$('editMsg').textContent='';$('editId').value=p?.id||'';$('editorTitle').textContent=p?'Edit Player':'Add Player';$('editName').value=p?.name||'';$('editRegion').value=p?.region||'NA';$('editSkin').value=p?.skin_url||'';$('resultsGrid').innerHTML=modes.map(m=>{const r=p?.results?.[m]||{};return `<div class="result"><h4>${modeNames[m]}</h4><label>Points<input class="points" data-mode="${m}" type="number" min="0" step="1" value="${r.points??''}" placeholder="blank"></label><label>Tier<input class="tier" data-mode="${m}" maxlength="3" value="${r.tier||''}" placeholder="HT1 / LT5"></label></div>`}).join('');$('editor').classList.remove('hidden');}
$('closeEditor').onclick=$('cancelEditor').onclick=()=> $('editor').classList.add('hidden');
$('playerForm').onsubmit=async e=>{e.preventDefault();$('editMsg').textContent='';const results={};modes.forEach(m=>{results[m]={points:document.querySelector(`.points[data-mode="${m}"]`).value,tier:document.querySelector(`.tier[data-mode="${m}"]`).value.toUpperCase()}});const body={name:$('editName').value,region:$('editRegion').value,skinUrl:$('editSkin').value,results};try{const id=$('editId').value;await api(id?`/api/admin/players/${id}`:'/api/admin/players',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('editor').classList.add('hidden');await loadPlayers();}catch(err){$('editMsg').textContent=err.message}};
async function deletePlayer(id){const p=players.find(x=>x.id===id);if(!p||!confirm(`Delete ${p.name}? This removes all mode results.`))return;try{await api('/api/admin/players/'+id,{method:'DELETE'});await loadPlayers()}catch(err){alert(err.message)}}
async function loadSettings(){try{const s=await api('/api/admin/settings');const fields=['overall','vanilla','uhc','pot','nethop','smp','sword','axe','mace'];$('iconForm').innerHTML=fields.map(m=>`<label>${m[0].toUpperCase()+m.slice(1)} image URL<input data-icon="icon_${m}" value="${escAttr(s['icon_'+m]||'')}" placeholder="https://.../image.png"></label>`).join('')}catch(err){$('iconMsg').textContent=err.message}}
$('saveIcons').onclick=async()=>{const body={};document.querySelectorAll('[data-icon]').forEach(i=>body[i.dataset.icon]=i.value.trim());try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(body)});$('iconMsg').textContent='Saved.';setTimeout(()=>$('iconMsg').textContent='',1500)}catch(err){$('iconMsg').textContent=err.message}};
$('pwForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/change-password',{method:'POST',body:JSON.stringify({currentPassword:$('currentPassword').value,newPassword:$('newPassword').value})});$('pwMsg').textContent='Password updated.';$('pwForm').reset()}catch(err){$('pwMsg').textContent=err.message}};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escAttr(s){return esc(s)}
check();
